### ISSUE TITLE
AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection' when running example.py

### ISSUE THREAD

**Issue by dave-schaefer** [leo27945875/Python_Stable_3D_Truss_Analysis#1]
Hello, 
when running the example.py with the current stable matplotlib==3.5.2, I get this error: AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection',

It works with matplotlib==3.4 though.

Results when running "python3 example.py":
numCube :     4, i :     1Traceback (most recent call last):
  File "/home/dave/Python_Stable_3D_Truss_Analysis/example.py", line 236, in <module>
    TestGenerateCubeTruss()
  File "/home/dave/Python_Stable_3D_Truss_Analysis/example.py", line 218, in TestGenerateCubeTruss
    trussList = GenerateRandomCubeTrusses(gridRange=GRID_RANGE,
  File "/home/dave/Python_Stable_3D_Truss_Analysis/slientruss3d/generate.py", line 324, in GenerateRandomCubeTrusses
    TrussPlotter(truss, 
  File "/home/dave/Python_Stable_3D_Truss_Analysis/slientruss3d/plot.py", line 125, in Plot
    plt.savefig(savePath)
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 958, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 3019, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 412, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 540, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 2810, in draw
    mimage._draw_list_compositing_images(
  File "/usr/lib/python3/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 451, in draw
    for artist in sorted(collections_and_patches,
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 426, in do_3d_projection
    signature = inspect.signature(artist.do_3d_projection)
AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

**Comment by leo27945875** [comment]
Hi, @dave-schaefer 
Please use matplotlib v3.4.3 for now. And maybe you can check this discussion:[https://github.com/matplotlib/matplotlib/issues/21688](https://github.com/matplotlib/matplotlib/issues/21688)

Best Regards

**Comment by leo27945875** [comment]
Hi, @dave-schaefer 
After v2.0.0 update, you can use matplotlib >= v3.5.2 now !

Best Regards
